import type { Metadata } from "next";
import { Baskervville, Poppins } from "next/font/google";
import "./globals.css";

const baskervvilleSerif = Baskervville({
  variable: "--font-baskervville-serif",
  subsets: ["latin"],
  weight: "400"
});

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Pomodrama",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baskervvilleSerif.variable} ${poppinsSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
